# This evaluation script is based on:
# https://github.com/dmlc/mxnet/blob/master/example/image-classification/score.py
#
# *.rec is generated by the following command:
# $im2rec_path $train_lst_path $train_lst_pref ./train.rec unchanged=1
# $im2rec_path $val_lst_path $val_lst_pref ./val.rec unchanged=1
#

# networks trained from scratch (with random initialization) on the official imagenet-1k dataset
python score.py --epoch 0 --model ./models/dpn68  --network dpn-68  2>&1 | tee -a  ./val.log
python score.py --epoch 0 --model ./models/dpn92  --network dpn-92  2>&1 | tee -a  ./val.log
python score.py --epoch 0 --model ./models/dpn98  --network dpn-98  2>&1 | tee -a  ./val.log
python score.py --epoch 0 --model ./models/dpn131 --network dpn-131 2>&1 | tee -a  ./val.log

# networks trained from scratch (with random initialization) on the customized imagenet-5k dataset
python score.py --epoch 0 --model ./models/dpn68-5k --network dpn-68_b --data-val '/tmp/val-5k.rec' --num-classes 4786 2>&1 | tee -a  ./val.log
python score.py --epoch 0 --model ./models/dpn92-5k --network dpn-92   --data-val '/tmp/val-5k.rec' --num-classes 4786 2>&1 | tee -a  ./val.log

# networks pre-trained on imagenet-5k from scratch (with random initialization)
# and then fine-tuned on the official imagenet-1k dataset
python score.py --epoch 0 --model ./models/dpn68-extra  --network dpn-68_b 2>&1 | tee -a  ./val.log
python score.py --epoch 0 --model ./models/dpn107-extra --network dpn-107  2>&1 | tee -a  ./val.log
